// If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a harder version of this one.

// A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

// For example, different possibilities are:

// Colour here:            G G        B G        R G        B R
// Becomes colour here:     G          R          B          G

function triangle(row) {
    while (row.length>1)
    {
      var r='';
      for (var i=0; i<row.length-1; ++i)
      {
        if (row[i]=='G' && row[i+1]=='G')
          r+='G';
        if (row[i]=='G' && row[i+1]=='R')
          r+='B';
        if (row[i]=='G' && row[i+1]=='B')
          r+='R';
        if (row[i]=='R' && row[i+1]=='G')
          r+='B';
        if (row[i]=='R' && row[i+1]=='R')
          r+='R';
        if (row[i]=='R' && row[i+1]=='B')
          r+='G';
        if (row[i]=='B' && row[i+1]=='G')
          r+='R';
        if (row[i]=='B' && row[i+1]=='B')
          r+='B';
        if (row[i]=='B' && row[i+1]=='R')
          r+='G';
      }
      row=r;
    }
    return row;
   }